import assert from "node:assert/strict";
import { readFile } from "node:fs/promises";
import test from "node:test";

function extractFunction(source, name) {
  const start = source.indexOf(`function ${name}(`);
  assert.notEqual(start, -1, `${name} must exist`);
  const open = source.indexOf("{", source.indexOf(")", start));
  let depth = 0;
  for (let i = open; i < source.length; i += 1) {
    if (source[i] === "{") depth += 1;
    if (source[i] === "}") depth -= 1;
    if (depth === 0) return source.slice(start, i + 1);
  }
  throw new Error(`Could not extract ${name}`);
}

test("TTLock SOT rows are generated by console continuity missing filter", async () => {
  const worker = await readFile("deploy-worker/src/index.js", "utf8");
  const mapper = extractFunction(worker, "empTtlockRoomsToConsoleUnresolvedArrears");
  const loader = extractFunction(worker, "empLoadTtlockConsoleUnresolvedForArrears");

  assert.match(mapper, /sotCurrentOccupiedCards/);
  assert.match(mapper, /sotLedgerPaymentCandidates/);
  assert.match(mapper, /knownArrearsBeds\.has/);
  assert.match(mapper, /anchoredShort/);
  assert.match(mapper, /gapDays>gapLimit/);
  assert.match(mapper, /amount_source:"owner_console_unresolved_missing"/);
  assert.match(loader, /ownerOverviewFetchTransactions/);
  assert.match(loader, /live_api_plus_cloud_ledger/);
});
