import { readdir, readFile } from "node:fs/promises";
import test from "node:test";
import assert from "node:assert/strict";

const draftDir = "migration-drafts";

async function draftFiles() {
  const names = await readdir(draftDir);
  return names.filter((name) => name.endsWith(".sql")).map((name) => `${draftDir}/${name}`);
}

test("commercial migration drafts do not use floating money types", async () => {
  for (const file of await draftFiles()) {
    const sql = await readFile(file, "utf8");
    assert.doesNotMatch(sql, /\b(REAL|FLOAT|DOUBLE)\b/i, `${file} must not use float types`);
  }
});

test("commercial bootstrap draft creates required accounting tables", async () => {
  const sql = await readFile("migration-drafts/002_commercial_bootstrap.sql", "utf8");
  const requiredTables = [
    "schema_migrations",
    "companies",
    "properties",
    "users",
    "property_memberships",
    "beds",
    "bed_rent_config_versions",
    "handover_sessions",
    "transactions",
    "receivables",
    "payments",
    "arrear_tasks",
    "deposit_ledger",
    "audit_events"
  ];

  for (const table of requiredTables) {
    assert.match(sql, new RegExp(`CREATE TABLE IF NOT EXISTS ${table}\\b`, "i"));
  }
});

test("commercial bootstrap draft uses tenant and property scope", async () => {
  const sql = await readFile("migration-drafts/002_commercial_bootstrap.sql", "utf8");
  assert.match(sql, /\bcompany_id TEXT NOT NULL\b/);
  assert.match(sql, /\bproperty_id TEXT NOT NULL\b/);
  assert.match(sql, /\bcompany_id, property_id\b/);
});

test("commercial bootstrap draft enforces transaction idempotency", async () => {
  const sql = await readFile("migration-drafts/002_commercial_bootstrap.sql", "utf8");
  assert.match(sql, /\bidempotency_key TEXT NOT NULL\b/);
  assert.match(sql, /CREATE UNIQUE INDEX IF NOT EXISTS idx_transactions_idempotency/i);
  assert.match(sql, /ON transactions\(company_id, property_id, idempotency_key\)/i);
});

test("commercial bootstrap draft stores money as integer fils", async () => {
  const sql = await readFile("migration-drafts/002_commercial_bootstrap.sql", "utf8");
  const requiredMoneyColumns = [
    "monthly_rent_fils",
    "half_month_rent_fils",
    "daily_rent_fils",
    "cash_handover_fils",
    "bank_transfer_total_fils",
    "gross_received_fils",
    "amount_fils",
    "due_fils",
    "paid_fils",
    "deficit_fils",
    "amount_due_fils",
    "amount_paid_fils",
    "amount_remaining_fils",
    "remaining_fils",
    "promise_amount_fils",
    "delta_fils",
    "balance_after_fils"
  ];

  for (const column of requiredMoneyColumns) {
    assert.match(sql, new RegExp(`\\b${column} INTEGER\\b`, "i"));
  }
});

test("migration promotion checklist requires commercial safety gates", async () => {
  const text = await readFile("MIGRATION_PROMOTION_CHECKLIST.md", "utf8");
  const requiredTerms = [
    "Financial Safety",
    "Multi-Tenant Isolation",
    "Audit And Soft-Delete",
    "Legacy Compatibility",
    "Backfill Plan",
    "Rollback Plan",
    "Production Cutover",
    "No-Go Conditions",
    "integer AED fils",
    "wrangler d1 execute homelink --local --persist-to <temp-dir>",
    "Do not promote or run the migration"
  ];

  for (const term of requiredTerms) {
    assert.match(text, new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"));
  }
});

test("legacy backfill map requires accounting reconciliation anchors", async () => {
  const text = await readFile("LEGACY_BACKFILL_MAP.md", "utf8");
  const requiredTerms = [
    "Backfill executed: no",
    "transactions",
    "receivables",
    "payments",
    "deposit_ledger",
    "entry_events",
    "audit_events",
    "integer AED fils",
    "per-session total differences",
    "per-tenant-card deposit differences",
    "No-Go Conditions"
  ];

  for (const term of requiredTerms) {
    assert.match(text, new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"));
  }
});

test("legacy backfill audit is read-only and generated", async () => {
  const text = await readFile("LEGACY_BACKFILL_AUDIT.md", "utf8");

  assert.match(text, /Generated by `scripts\/audit-legacy-backfill\.mjs`/);
  assert.match(text, /Mode: read-only static audit/);
  assert.match(text, /No D1 connection was opened/);
  assert.match(text, /No SQL was executed/);
  assert.match(text, /Legacy-To-Commercial Mapping/);
});

test("legacy reconciliation spec requires dry-run accounting outputs", async () => {
  const text = await readFile("LEGACY_RECONCILIATION_SPEC.md", "utf8");
  const requiredTerms = [
    "Backfill executed: no",
    "legacy-reconciliation-report.json",
    "legacy-reconciliation-exceptions.csv",
    "money_totals_fils",
    "session_totals",
    "receivable_totals",
    "deposit_balances",
    "audit_coverage",
    "idempotency",
    "P0 Exceptions"
  ];

  for (const term of requiredTerms) {
    assert.match(text, new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"));
  }
});

test("legacy reconciliation template is generated and non-executing", async () => {
  const jsonText = await readFile(
    "reconciliation-templates/legacy-reconciliation-report.template.json",
    "utf8"
  );
  const mdText = await readFile(
    "reconciliation-templates/legacy-reconciliation-report.template.md",
    "utf8"
  );
  const csvText = await readFile(
    "reconciliation-templates/legacy-reconciliation-exceptions.template.csv",
    "utf8"
  );
  const report = JSON.parse(jsonText);

  assert.equal(report.run.mode, "dry-run-template");
  assert.equal(report.run.source, "not-connected");
  assert.match(mdText, /No D1 connection was opened/);
  assert.match(mdText, /money totals in integer AED fils/);
  assert.match(csvText, /severity,code,legacy_table/);
});

test("commercial entry write contract requires atomic audited server-side writes", async () => {
  const text = await readFile("COMMERCIAL_ENTRY_WRITE_CONTRACT.md", "utf8");
  const requiredTerms = [
    "not executable code",
    "Production database mutation: not executed",
    "Authenticate request",
    "company_id",
    "property_id",
    "property_memberships",
    "createRentEntryDraft",
    "atomic write unit",
    "transactions",
    "receivables",
    "payments",
    "arrear_tasks",
    "audit_events",
    "handover_sessions",
    "idempotency key",
    "transactions(company_id, property_id, idempotency_key)",
    "uniqueness constraint",
    "Frontend totals are display-only",
    "must not be the source of truth",
    "REAL",
    "FLOAT"
  ];

  for (const term of requiredTerms) {
    assert.match(text, new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"));
  }
});

test("employee entry Worker migration plan preserves commercial safety gates", async () => {
  const text = await readFile("EMPLOYEE_ENTRY_WORKER_MIGRATION_PLAN.md", "utf8");
  const requiredTerms = [
    "Production deployment: not executed",
    "Production database mutation: not executed",
    "/api/employee/entry",
    "clean-bootstrap P0",
    "idempotency",
    "integer fils",
    "property membership",
    "EMPLOYEE_ENTRY_COMMERCIAL_V1",
    "npm run probe:clean-bootstrap",
    "rollback"
  ];

  for (const term of requiredTerms) {
    assert.match(text, new RegExp(term.replace(/[.*+?^${}()|[\]\\]/g, "\\$&"), "i"));
  }
});
