import assert from 'node:assert/strict';
import test from 'node:test';
import {prepareOwnerBedTransferVoid} from '../modules/owner-corrections/bed-transfer-void.mjs';
import {projectBedTransferLineage} from '../modules/owner-history/bed-transfer-lineage-projection.mjs';
import {projectBedTransferFinanceAndArrears} from '../modules/finance/bed-transfer-finance-arrears-projection.mjs';
import {projectBedTransferOwnerTodos} from '../modules/owner-todo/bed-transfer-owner-todo.mjs';

const transfer={event_type:'bed_transfer',transfer_anchor_id:'transfer-anchor-opaque-146-111',transfer_lineage_id:'transfer-lineage-opaque-146',from_bed:'146',to_bed:'111',corpid:'corp',fee_mode:'waived',fee_amount_aed:0,fee_waiver_reason:'CONTROLLED_BETA_TEST_NO_CHARGE',ttlock_sequence:'employee_first_pre_move',reconciliation_required:true};
const paidTransfer={...transfer,fee_mode:'paid',fee_amount_aed:50,payment_method:'cash',fee_due_date:'',fee_waiver_reason:'',bed_price_difference_mode:'none',bed_price_difference_amount_aed:0};
const request={transfer_anchor_id:transfer.transfer_anchor_id,reason:'CONTROLLED_BETA_TEST_CLEANUP',idempotency_key:'cleanup-1'};
const build=()=>prepareOwnerBedTransferVoid({request,effective_transfer:transfer,corpid:'corp',accepted_at:'2026-07-13T12:00:00Z',owner_reference:'manager'},{idFactory:kind=>kind==='void_session_id'?'void-session-opaque':'void-anchor-opaque'});
const retained=()=>prepareOwnerBedTransferVoid({request:{...request,financial_disposition:'retain_earned_income'},effective_transfer:paidTransfer,corpid:'corp',accepted_at:'2026-07-13T12:00:00Z',owner_reference:'manager'},{idFactory:kind=>kind==='void_session_id'?'void-session-retained':'void-anchor-retained'});

test('prepares one additive zero-finance void anchor without mutating the transfer',()=>{const r=build();assert.equal(r.ok,true);assert.equal(r.entry.event_type,'void_transfer');assert.equal(r.entry.target_transfer_anchor_id,transfer.transfer_anchor_id);assert.equal(r.entry.original_transfer_mutated,false);assert.equal(r.entry.hard_delete,false);assert.equal(r.entry.ttlock_mutated,false);assert.deepEqual(r.entry.finance_effect,{rent_income:0,deposit_received:0,deposit_refund:0,arrears_repaid:0,bed_transfer_fee_income:0});assert.equal(JSON.parse(r.entries_json).entries.length,1);});
test('void request rejects client server fields and corpid mismatch before write',()=>{assert.equal(prepareOwnerBedTransferVoid({request:{...request,corpid:'evil'},effective_transfer:transfer,corpid:'corp'}).error_code,'BED_TRANSFER_VOID_FIELD_FORBIDDEN');assert.equal(prepareOwnerBedTransferVoid({request,effective_transfer:transfer,corpid:'other'}).error_code,'BED_TRANSFER_VOID_CORPID_MISMATCH');});
test('void restores lineage and clears effective finance and todo projections',()=>{const v=build().entry;const lineage=projectBedTransferLineage({transfer_anchors:[transfer],void_anchors:[v]});assert.equal(lineage.current_bed,'146');const finance=projectBedTransferFinanceAndArrears({corpid:'corp',archive_entries:[transfer,v],source_arrears:[]});assert.equal(finance.effective_transfer_events.length,0);assert.equal(finance.finance.bed_transfer_fee_income,0);const todo=projectBedTransferOwnerTodos({corpid:'corp',archive_entries:[transfer,v],access_snapshots:{}});assert.equal(todo.todos.length,0);});
test('retain earned income void reverses lineage while preserving paid cash fee',()=>{const v=retained().entry;assert.equal(v.financial_disposition,'retain_earned_income');assert.equal(v.paid_transfer_fee_amount_aed,50);assert.equal(v.refund_required,false);assert.equal(v.automatic_refund_created,false);const lineage=projectBedTransferLineage({transfer_anchors:[paidTransfer],void_anchors:[v]});assert.equal(lineage.current_bed,'146');const finance=projectBedTransferFinanceAndArrears({corpid:'corp',archive_entries:[paidTransfer,v],source_arrears:[]});assert.equal(finance.effective_transfer_events.length,0);assert.equal(finance.finance.bed_transfer_fee_income,50);assert.equal(finance.finance.cash_received,50);assert.equal(finance.finance.bank_received,0);assert.equal(finance.finance.gross_received,50);assert.equal(finance.reconciliation_warnings.length,0);const todo=projectBedTransferOwnerTodos({corpid:'corp',archive_entries:[paidTransfer,v],access_snapshots:{}});assert.equal(todo.todos.some(row=>row.task_type==='BED_TRANSFER_VOID_FINANCIAL_RECONCILIATION_REQUIRED'),false);});
test('retain earned income disposition is strict while legacy void remains unchanged',()=>{assert.equal(prepareOwnerBedTransferVoid({request:{...request,financial_disposition:'refund'},effective_transfer:transfer,corpid:'corp'}).error_code,'BED_TRANSFER_VOID_FINANCIAL_DISPOSITION_INVALID');assert.equal(prepareOwnerBedTransferVoid({request:{...request,financial_disposition:'retain_earned_income'},effective_transfer:{...transfer,payment_method:''},corpid:'corp'}).error_code,'BED_TRANSFER_VOID_RETAIN_EARNED_INCOME_NOT_APPLICABLE');assert.equal(build().entry.financial_disposition,undefined);});
