import fs from "node:fs";
import path from "node:path";
import prettier from "prettier";

const root = process.cwd();
const outputPath = path.join(root, "DATABASE_STATIC_SCAN.md");
const checkOnly = process.argv.includes("--check");

const scanFiles = [
  path.join(root, "deploy-worker", "src", "index.js"),
  ...safeList(path.join(root, "migrations")).filter((file) => file.endsWith(".sql")),
  ...safeList(path.join(root, "migration-drafts")).filter((file) => file.endsWith(".sql"))
].filter((file) => fs.existsSync(file));

function safeList(dir) {
  if (!fs.existsSync(dir)) return [];
  return fs.readdirSync(dir, { withFileTypes: true }).flatMap((entry) => {
    const fullPath = path.join(dir, entry.name);
    return entry.isDirectory() ? safeList(fullPath) : [fullPath];
  });
}

function rel(file) {
  return path.relative(root, file).replaceAll("\\", "/");
}

function lineNumberFor(text, index) {
  return text.slice(0, index).split(/\r?\n/).length;
}

function finding(severity, file, line, issue, evidence) {
  return {
    severity,
    file: rel(file),
    line,
    issue,
    evidence: evidence.replace(/\s+/g, " ").trim().slice(0, 220)
  };
}

const findings = [];
const tableNames = new Map();

for (const file of scanFiles) {
  const text = fs.readFileSync(file, "utf8");
  const isWorker = rel(file) === "deploy-worker/src/index.js";

  for (const match of text.matchAll(
    /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z0-9_]+)/gi
  )) {
    const name = match[1];
    if (!tableNames.has(name)) tableNames.set(name, new Set());
    tableNames.get(name).add(rel(file));
    if (isWorker) {
      findings.push(
        finding(
          "P1",
          file,
          lineNumberFor(text, match.index ?? 0),
          "Runtime CREATE TABLE appears in Worker source",
          match[0]
        )
      );
    }
  }

  for (const match of text.matchAll(/ALTER\s+TABLE\s+([A-Za-z0-9_]+)/gi)) {
    if (isWorker) {
      findings.push(
        finding(
          "P1",
          file,
          lineNumberFor(text, match.index ?? 0),
          "Runtime ALTER TABLE appears in Worker source",
          match[0]
        )
      );
    }
  }

  for (const match of text.matchAll(/\b(REAL|FLOAT|DOUBLE)\b/gi)) {
    findings.push(
      finding(
        "P0",
        file,
        lineNumberFor(text, match.index ?? 0),
        "Decimal/money precision risk keyword",
        match[0]
      )
    );
  }

  for (const match of text.matchAll(/DELETE\s+FROM\s+([A-Za-z0-9_]+)/gi)) {
    findings.push(
      finding("P0", file, lineNumberFor(text, match.index ?? 0), "Hard delete statement", match[0])
    );
  }
}

function buildReport() {
  const tableRows = [...tableNames.entries()]
    .sort(([a], [b]) => a.localeCompare(b))
    .map(([table, files]) => `| \`${table}\` | ${[...files].sort().join(", ")} |`);

  const findingRows = findings.map(
    (row) =>
      [
        `| ${row.severity}`,
        `\`${row.file}:${row.line}\``,
        row.issue,
        `\`${row.evidence.replaceAll("|", "\\|")}\``
      ].join(" | ") + " |"
  );

  return [
    "# Database Static Scan",
    "",
    "Date: 2026-05-23",
    "Source: generated by `scripts/audit-db.mjs`",
    "Production calls: none",
    "Production database mutation: none",
    "",
    "This is a static scan artifact. It does not replace `DATABASE_AUDIT.md`, which contains manual commercial database review and migration recommendations.",
    "",
    "## Scan Inputs",
    "",
    ...scanFiles.map((file) => `- \`${rel(file)}\``),
    "",
    "## Tables Detected",
    "",
    "| Table | Source Files |",
    "| --- | --- |",
    ...(tableRows.length ? tableRows : ["| n/a | No CREATE TABLE statements detected. |"]),
    "",
    "## Findings",
    "",
    "| Severity | Location | Issue | Evidence |",
    "| --- | --- | --- | --- |",
    ...(findingRows.length
      ? findingRows
      : ["| P3 | n/a | No static findings from basic scan. | n/a |"]),
    "",
    "## Commercial Interpretation",
    "",
    "- P0 findings are launch blockers until the commercial schema moves money to integer minor units and removes hard deletes from normal business flows.",
    "- P1 runtime DDL findings confirm schema changes must move out of Worker request paths and into reviewed migrations.",
    "- This scan is intentionally read-only and does not connect to D1.",
    ""
  ].join("\n");
}

const nextReport = await prettier.format(buildReport(), { parser: "markdown" });

if (checkOnly) {
  const current = fs.existsSync(outputPath) ? fs.readFileSync(outputPath, "utf8") : "";
  if (current !== nextReport) {
    throw new Error("DATABASE_STATIC_SCAN.md is out of date. Run `npm run audit:db`.");
  }
  console.log("Database static scan is up to date.");
} else {
  fs.writeFileSync(outputPath, nextReport);
  console.log(
    `Database static scan written: ${findings.length} findings, ${tableNames.size} tables`
  );
}
