import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const files = [
  path.join(root, "deploy-worker", "src", "index.js"),
  path.join(root, "migrations", "001_employee_anchor_schema.sql")
].filter((file) => fs.existsSync(file));

const findings = [];
const tableNames = new Set();

for (const file of files) {
  const text = fs.readFileSync(file, "utf8");
  for (const match of text.matchAll(
    /CREATE\s+TABLE\s+(?:IF\s+NOT\s+EXISTS\s+)?([A-Za-z0-9_]+)/gi
  )) {
    tableNames.add(match[1]);
  }
  for (const match of text.matchAll(/\b(REAL|FLOAT|DOUBLE)\b/gi)) {
    findings.push({ severity: "P0", file, issue: `Money/decimal risk keyword: ${match[1]}` });
  }
  for (const match of text.matchAll(/DELETE\s+FROM\s+([A-Za-z0-9_]+)/gi)) {
    findings.push({ severity: "P0", file, issue: `Hard delete statement: ${match[0]}` });
  }
  if (
    /CREATE\s+TABLE[\s\S]{0,2000}async function|async function[\s\S]{0,2000}CREATE\s+TABLE/i.test(
      text
    )
  ) {
    findings.push({
      severity: "P1",
      file,
      issue: "CREATE TABLE appears in application/request code path"
    });
  }
}

const lines = [
  "# Database Audit",
  "",
  "Generated by `scripts/audit-db.mjs`.",
  "",
  "## Tables Detected",
  "",
  ...[...tableNames].sort().map((name) => `- \`${name}\``),
  "",
  "## Findings",
  "",
  "| Severity | File | Issue |",
  "| --- | --- | --- |"
];

for (const finding of findings) {
  lines.push(
    `| ${finding.severity} | \`${path.relative(root, finding.file).replaceAll("\\", "/")}\` | ${finding.issue} |`
  );
}

if (!findings.length) lines.push("| P3 | n/a | No static findings from basic scan. |");

fs.writeFileSync(path.join(root, "DATABASE_AUDIT.md"), `${lines.join("\n")}\n`);
console.log(`Database audit written: ${findings.length} findings, ${tableNames.size} tables`);
