import fs from "node:fs";
import path from "node:path";

const root = process.cwd();
const workerPath = path.join(root, "deploy-worker", "src", "index.js");
const source = fs.readFileSync(workerPath, "utf8");

const routeRegex =
  /path\s*={2,3}\s*["`]([^"`]+)["`]\s*&&\s*method\s*={2,3}\s*["`]([A-Z]+)["`]|path\s*={2,3}\s*["`]([^"`]+)["`]/g;
const routes = new Map();

for (const match of source.matchAll(routeRegex)) {
  const pathValue = match[1] || match[3];
  const method = match[2] || "ANY";
  if (!pathValue || !pathValue.startsWith("/")) continue;
  const key = `${method} ${pathValue}`;
  routes.set(key, { method, path: pathValue });
}

const lines = [
  "# API Inventory",
  "",
  "Generated by `scripts/audit-api.mjs`.",
  "",
  "| Method | Path | Auth expectation | Initial risk | Notes |",
  "| --- | --- | --- | --- | --- |"
];

for (const route of [...routes.values()].sort((a, b) =>
  `${a.path} ${a.method}`.localeCompare(`${b.path} ${b.method}`)
)) {
  const auth =
    route.path.startsWith("/auth/") || route.path === "/health"
      ? "public/login route"
      : "requires server auth review";
  const risk = route.path.includes("delete") ? "P0" : route.path.startsWith("/api/") ? "P1" : "P2";
  lines.push(
    `| ${route.method} | \`${route.path}\` | ${auth} | ${risk} | Source scan only; manual review required. |`
  );
}

fs.writeFileSync(path.join(root, "API_INVENTORY.md"), `${lines.join("\n")}\n`);
console.log(`API inventory written: ${routes.size} routes`);
